[tool.poetry]
name = "tutorial-pytest"
version = "0.1.0"
description = ""
authors = ["Min"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.3"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
